version: '3.3'
services:
  db:
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=testdb
    networks: 
      - red
    volumes:
      - 'mi-volumen:/var/lib/mysql'
    image: 'mariadb:latest'
  web:
    container_name: spring
    env_file: .env
    networks: 
      - red
    ports: 
      - "8080:8080"
    build: .
    depends_on: 
      - db

networks: 
  red:
volumes: 
  mi-volumen: