version: '3.3'
services:
  db:
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=testdb
    networks: 
      - red
    volumes:
      - 'mi-volumen:/var/lib/mysql'
    image: 'mariadb:latest'
  web:
    container_name: spring
    env_file: .env
    networks: 
      - red
    build: 
      context: back
    depends_on: 
      - db
  front:
    container_name: vue
    networks: 
      - red
    ports: 
      - "80:80"
    build: 
      context: vue-js-crud-example

networks: 
  red:
volumes: 
  mi-volumen: