apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: mi-espacio
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: us.gcr.io/proyecto-gen2/vue-front
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mi-servicio-front
  namespace: mi-espacio
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer