apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: springapp
        env:
        - name: DB_PASS
          value: "123456"
        - name: DB_NAME
          value: testdb
        - name: DB_HOST
          value: "192.168.1.9"
        - name: DB_USER
          value: root
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: mi-servicio-spring
spec:
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP